# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: token.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btoken.proto\x12\rairliner_grpc\"E\n\x0fTokenReqMessage\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08passcode\x18\x03 \x01(\t\"2\n\x0fTokenResMessage\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0f\n\x07isvalid\x18\x02 \x01(\x08\x32\x7f\n UserValidationForTokenGeneration\x12[\n\x17ValidateUserCredentials\x12\x1e.airliner_grpc.TokenReqMessage\x1a\x1e.airliner_grpc.TokenResMessage\"\x00\x62\x06proto3')



_TOKENREQMESSAGE = DESCRIPTOR.message_types_by_name['TokenReqMessage']
_TOKENRESMESSAGE = DESCRIPTOR.message_types_by_name['TokenResMessage']
TokenReqMessage = _reflection.GeneratedProtocolMessageType('TokenReqMessage', (_message.Message,), {
  'DESCRIPTOR' : _TOKENREQMESSAGE,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:airliner_grpc.TokenReqMessage)
  })
_sym_db.RegisterMessage(TokenReqMessage)

TokenResMessage = _reflection.GeneratedProtocolMessageType('TokenResMessage', (_message.Message,), {
  'DESCRIPTOR' : _TOKENRESMESSAGE,
  '__module__' : 'token_pb2'
  # @@protoc_insertion_point(class_scope:airliner_grpc.TokenResMessage)
  })
_sym_db.RegisterMessage(TokenResMessage)

_USERVALIDATIONFORTOKENGENERATION = DESCRIPTOR.services_by_name['UserValidationForTokenGeneration']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOKENREQMESSAGE._serialized_start=30
  _TOKENREQMESSAGE._serialized_end=99
  _TOKENRESMESSAGE._serialized_start=101
  _TOKENRESMESSAGE._serialized_end=151
  _USERVALIDATIONFORTOKENGENERATION._serialized_start=153
  _USERVALIDATIONFORTOKENGENERATION._serialized_end=280
# @@protoc_insertion_point(module_scope)
