# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import airliner_grpc.token_pb2 as token__pb2


class UserValidationForTokenGenerationStub(object):
    """buf:lint:ignore SERVICE_SUFFIX
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateUserCredentials = channel.unary_unary(
                '/airliner_grpc.UserValidationForTokenGeneration/ValidateUserCredentials',
                request_serializer=token__pb2.TokenReqMessage.SerializeToString,
                response_deserializer=token__pb2.TokenResMessage.FromString,
                )


class UserValidationForTokenGenerationServicer(object):
    """buf:lint:ignore SERVICE_SUFFIX
    """

    def ValidateUserCredentials(self, request, context):
        """buf:lint:ignore RPC_REQUEST_STANDARD_NAME
        buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserValidationForTokenGenerationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateUserCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateUserCredentials,
                    request_deserializer=token__pb2.TokenReqMessage.FromString,
                    response_serializer=token__pb2.TokenResMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'airliner_grpc.UserValidationForTokenGeneration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserValidationForTokenGeneration(object):
    """buf:lint:ignore SERVICE_SUFFIX
    """

    @staticmethod
    def ValidateUserCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/airliner_grpc.UserValidationForTokenGeneration/ValidateUserCredentials',
            token__pb2.TokenReqMessage.SerializeToString,
            token__pb2.TokenResMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
