"""Add index to username and email

Revision ID: 40c28f8c1faa
Revises: 
Create Date: 2023-09-07 23:01:00.296144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40c28f8c1faa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('ID', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('FirstName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('LastName', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('DateOfBirth', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('UpdatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name='users_pkey'),
    sa.UniqueConstraint('Email', name='users_Email_key'),
    sa.UniqueConstraint('Username', name='users_Username_key')
    )
    # ### end Alembic commands ###
