# BUILD file for Protocol Buffers

package(default_visibility = ["//visibility:public"])

# Note: Proto compilation rules are temporarily disabled
# Will re-enable once rules_proto is properly configured in WORKSPACE
# load("@rules_proto//proto:defs.bzl", "proto_library")
# 
# proto_library(
#     name = "token_proto",
#     srcs = ["token_proto_v1/token.proto"],
# )

