"""added indexand uniquecons for the token, userid

Revision ID: b2645dcc2eb1
Revises: 
Create Date: 2023-09-08 13:09:33.052383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2645dcc2eb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('ID', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('UserID', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Token', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('Expiry', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('UpdatedAt', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ID', name='tokens_pkey'),
    sa.UniqueConstraint('UserID', name='tokens_UserID_key')
    )
    # ### end Alembic commands ###
